add_executable(ServerEngineDatagramTransportExample main.cpp)
target_link_libraries(ServerEngineDatagramTransportExample PRIVATE ServerEngineDll)
serverengine_target_defaults(ServerEngineDatagramTransportExample)
set_target_properties(ServerEngineDatagramTransportExample PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}
    VS_DEBUGGER_WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
